# -*- coding: utf-8 -*-
"""trainingday-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwtu7f-Lj6DKe8AHkWv6k6lWs7T0_rrj
"""

def myFun(n):
    if n==0:
        return
    print(n,end=" ")
    myFun(n-1)

n=5
myFun(n)

def myFun(n):
    if n == 0:
        return
    myFun(n - 1)
    print(n, end=" ")

n = 5
myFun(n)

def myFun(n):
    if n==0:
        return
    print(n,end=" ")
    myFun(n-2)

n=10
myFun(n)

def myFun(n):
    if n==0:
        return
    myFun(n-2)
    print(n,end=" ")

n=10
myFun(n)

def myFun(n):
    if n == 0:
        return

    print(n, end=" ")

    if n > 1:
        myFun(n - 1)
        print(n, end=" ")

myFun(5)

def myFun(n):
    if n==0:
        return 200
    t=myFun(n-1)
    print(n,end=" ")
    return t

n=5
myFun(n)

def myFun(n):
    if n == 0:
        return
    if n % 2==0:
        print(n, end=" ")

    if n > 1:
        myFun(n - 1)
        if n % 2==0 and n>3:
            print(n, end=" ")

myFun(10)

def myFun(n):
    if n == 0:
        return

    print(n, end=" ")

    if n > 1 and n>3:
        myFun(n - 2)
        print(n, end=" ")

myFun(10)

def fun(n,m=0):
    if n==m:
        return
    print(m+1,end=" ")
    fun(n,m+1)
    print(m+1,end=" ")

n=5
fun(n)

def fun(n):
    if n==1:
        return 0
    elif n%2==0:
        return 1+fun(n//2)
    else:
        return 1+min(fun(n-1),fun(n+1))
n=15
print(fun(n))

def wildfire(grid,i,j):
    if i<0 or i>=len(grid) or j<0 or j>=len(grid[0]) or grid[i][j]!=1:
        return
    grid[i][j]=2
    wildfire(grid,i+1,j)
    wildfire(grid,i-1,j)
    wildfire(grid,i,j+1)
    wildfire(grid,i,j-1)
matrix=[[1,1,1,1],
        [1,0,0,0],
        [0,0,1,1],
        [1,0,0,0]]
wildfire(matrix,0,0)
c=0
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        if matrix[i][j]==1:
            c+=1
print(c)

*733*
class Solution:
    def floodFill(self, image: List[List[int]], sr: int, sc: int, color: int) -> List[List[int]]:

        original = image[sr][sc]

        if original == color:
            return image

        def fill(i, j):
            if (i < 0 or i >= len(image) or
                j < 0 or j >= len(image[0]) or
                image[i][j] != original):
                return

            image[i][j] = color

            fill(i + 1, j)
            fill(i - 1, j)
            fill(i, j + 1)
            fill(i, j - 1)

        fill(sr, sc)
        return image

*200*
class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        if not grid:
            return 0
        def count_island(grid,i,j):
            if i<0 or i>=len(grid) or j<0 or j>=len(grid[0]) or grid[i][j]!='1':
                return
            grid[i][j]='2'
            count_island(grid,i+1,j)
            count_island(grid,i-1,j)
            count_island(grid,i,j-1)
            count_island(grid,i,j+1)
        c=0
        for i in range(len(grid)):
            for j in range(len(grid[0])):
                if grid[i][j]=='1':
                    count_island(grid,i,j)
                    c+=1
        return c

def maze(grid,path,i,j,n):
    if i==n and j==n:
        print(path)
        return
    if i+1<=n and grid[i+1][j]==1:
        maze(grid,path+'D',i+1,j,n)
    if j+1<=n and grid[i][j+1]==1:
        maze(grid,path+'R',i,j+1,n)

grid=[[1,1,0,1],
     [1,1,0,1],
     [0,1,0,0],
     [1,1,1,1]]

n=len(grid)
maze(grid,"",0,0,n-1)