# -*- coding: utf-8 -*-
"""trainingday-9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ja0enLCOFIoXGfIugG_CNxjzYZ8MIF8O
"""

*1484*
SELECT
    sell_date,
    COUNT(DISTINCT product) AS num_sold,
    GROUP_CONCAT(DISTINCT product ORDER BY product SEPARATOR ',') AS products
FROM Activities
GROUP BY sell_date
ORDER BY sell_date;

class Node :
    def __init__(self, data) :
        self.data = data
        self.left = None
        self.right = None
class BST :
    def __init__(self) :
        self.root = None
    def insert(self, node, data) :
        if node is None:
            return Node(data)
        if data < node.data :
            node.left = self.insert(node.left, data)
        elif data > node.data :
            node.right = self.insert(node.right, data)
        return node
    def inorder(self, root) :
        if root is None :
            return
        self.inorder(root.left)
        print(root.data)
        self.inorder(root.right)
tree = BST()
tree.root = tree.insert(tree.root, 5)
tree.root = tree.insert(tree.root, 3)
tree.root = tree.insert(tree.root, 1)
tree.root = tree.insert(tree.root, 2)
tree.inorder(tree.root)

*PREORDER*
def preOrder(root):
    if root is None:
        return

    print(root.info, end=" ")
    preOrder(root.left)
    preOrder(root.right)

*POSTORDER*
def postOrder(root):
    if root is None:
        return

    postOrder(root.left)
    postOrder(root.right)
    print(root.info, end=" ")

*INORDER*
def inOrder(root):
    if root is None:
        return

    inOrder(root.left)
    print(root.info, end=" ")
    inOrder(root.right)

*LEVELORDER*
from collections import deque

def levelOrder(root):
    if root is None:
        return

    q = deque([root])

    while q:
        node = q.popleft()
        print(node.info, end=" ")

        if node.left:
            q.append(node.left)
        if node.right:
            q.append(node.right)

*HEIGHT OF BINARY TREE*
def height(root):
    if root is None:
        return -1
    return 1+max(height(root.left),height(root.right))

*LOWEST COMMON ANCESTOR*
def lca(root, v1, v2):
    if root.info>v1 and root.info>v2:
        return lca(root.left,v1,v2)
    elif root.info<v1 and root.info<v2:
        return lca(root.right,v1,v2)
    else:
        return root

tree = BinarySearchTree()

*IS THIS A BST*
class node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

def newNode():
    temp = node(-1)
    temp.left = None
    temp.right = None
    return(temp);

""" Node is defined as
class node:
  def __init__(self, data):
      self.data = data
      self.left = None
      self.right = None
"""
def check_binary_search_tree_(root):
    res=[]
    def inorder(root):
        if root is None:
            return 0
        inorder(root.left)
        res.append(root.data)
        inorder(root.right)
    inorder(root)
    for i in range(len(res)-1):
        if (res[i]>=res[i+1]):
            return False
    return True
ht = int(input())