# -*- coding: utf-8 -*-
"""trainingday-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sNm56c7SzGW0r60jIWsC4SVW4F3PIS0
"""

l=list(map(int,input().split()))
k=int(input("enter no of rotations:"))
for i in range(k):
    temp=l[0]

l = list(map(int, input().split()))
k = int(input("enter no of rotations:"))

n = len(l)
r = [0] * n
j = 0

for i in range(k, n):
    r[j] = l[i]
    j += 1

for i in range(k):
    r[j] = l[i]
    j += 1

print(r)

l=list(map(int,input().split()))
k=int(input("enter no of rotation:"))

n = len(l)
r = [0] * n
j = 0

for i in range(n - k, n):
    r[j] = l[i]
    j += 1

for i in range(n - k):
    r[j] = l[i]
    j += 1

print(r)

l1=[1,5,6]              //two pointer problems
l2=[2,3,4,7,8,9]
l3=[]
i,j=0,0
while i < len(l1) and j < len(l2):
    if l1[i]<l2[j]:
        l3.append(l1[i])
        i+=1
    else:
        l3.append(l2[j])
        j+=1
while i < len(l1):
    l3.append(l1[i])
    i+=1
while j < len(l2):
    l3.append(l2[j])
    j+=1
print(l3)

*189*
class Solution:
    def rotate(self, nums: List[int], k: int) -> None:
        n = len(nums)
        k = k % n

        temp = [0] * n
        j = 0

        for i in range(n - k, n):
            temp[j] = nums[i]
            j += 1

        for i in range(n - k):
            temp[j] = nums[i]
            j += 1

        for i in range(n):
            nums[i] = temp[i]

*125*
class Solution:
    def isPalindrome(self, s: str) -> bool:
        i,j=0,len(s)-1
        s=s.lower()
        while i<j:
            while i<j and not s[i].isalnum():
                i+=1
            while i<j and not s[j].isalnum():
                j-=1
            if s[i]!=s[j]:
                return False
            i+=1
            j-=1
        return True

*680*
class Solution:
    def validPalindrome(self, s: str) -> bool:
        i, j = 0, len(s) - 1

        while i < j:
            if s[i] != s[j]:
                skip_left = s[i + 1:j + 1]
                skip_right = s[i:j]

                if skip_left == skip_left[::-1] or skip_right == skip_right[::-1]:
                    return True
                else:
                    return False

            i += 1
            j -= 1

        return True

books=list(map(int,input().split()))
k=int(input("enter no"))
n=len(books)
s=sum(books[:k])
m=s
for i in range(1,n-k+1):
    s=s-books[i-1]+books[i+k-1]
    m=max(m,s)
print(m)

*263*
class Solution:
    def isUgly(self, n: int) -> bool:
        if n<=0:
            return False
        for i in [2,3,5]:
            while n%i==0:
                n=n//i
        return n==1