# -*- coding: utf-8 -*-
"""trainingday-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbI9zlVahvrLa3W2ySub4kc_iBjNiqeG
"""

*79*
from typing import List

class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:

        def possible(i, j, k):
            if k == len(word):
                return True

            if (i < 0 or i >= len(board) or
                j < 0 or j >= len(board[0]) or
                board[i][j] != word[k]):
                return False

            temp = board[i][j]
            board[i][j] = "#"

            found = (
                possible(i - 1, j, k + 1) or
                possible(i + 1, j, k + 1) or
                possible(i, j - 1, k + 1) or
                possible(i, j + 1, k + 1)
            )

            board[i][j] = temp  # backtrack
            return found

        for i in range(len(board)):
            for j in range(len(board[0])):
                if possible(i, j, 0):
                    return True

        return False

*20*
class Solution:
    def isValid(self, s: str) -> bool:
        st=[]
        for i in s:
            if i=='{':
                st.append('}')
            elif i=='[':
                st.append(']')
            elif i=='(':
                st.append(')')
            elif len(st)==0 or st.pop()!=i:
                return False
        return len(st)==0

*844*
class Solution:
    def backspaceCompare(self, s: str, t: str) -> bool:

        def build(string):
            stack = []

            for ch in string:
                if ch == '#':
                    if stack:
                        stack.pop()
                else:
                    stack.append(ch)

            return "".join(stack)

        return build(s) == build(t)

*71*
class Solution:
    def simplifyPath(self, path: str) -> str:
        stack = []

        for part in path.split('/'):
            if part == '' or part == '.':
                continue
            elif part == '..':
                if stack:
                    stack.pop()
            else:
                stack.append(part)

        return '/' + '/'.join(stack)

*1700*
class Solution:
    def countStudents(self, students: List[int], sandwiches: List[int]) -> int:
        n=len(students)
        while students and sandwiches and sandwiches[0] in students:
            if students[0]!=sandwiches[0]:
                students.append(students.pop(0))
            else:
                n-=1
                students.pop(0)
                sandwiches.pop(0)
        return n

*1544*
class Solution:
    def makeGood(self, s: str) -> str:
        stack = []

        for ch in s:
            if stack and abs(ord(stack[-1]) - ord(ch)) == 32:
                stack.pop()
            else:
                stack.append(ch)

        return "".join(stack)

*496*
class Solution:
    def nextGreaterElement(self, nums1: List[int], nums2: List[int]) -> List[int]:
        d={}
        st=[]
        for cur in nums2:
            while st and st[-1]<cur:
                ele=st.pop()
                d[ele]=cur
            st.append(cur)
        while st:
            d[st.pop()]=-1
        res=[]
        for i in nums1:
            res.append(d[i])
        return res

*739*
class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        n = len(temperatures)
        ans = [0] * n
        stack = []

        for i in range(n):
            while stack and temperatures[i] > temperatures[stack[-1]]:
                idx = stack.pop()
                ans[idx] = i - idx

            stack.append(i)

        return ans