# -*- coding: utf-8 -*-
"""trainingday-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZQ4qKfeMiAMAsHwty4enaeSA_iPo7eP
"""

list=[2,1,6,2,1,2,4,7,8,1,2]
k=10
r,l,s,m=0,0,0,0

while r<len(list):
    s+=list[r]
    while s>k:
        s-=list[l]
        l+=1
    length=r-l+1
    m=max(m,length)
    r+=1
print(m)

*713*
class Solution:
    def numSubarrayProductLessThanK(self, nums: List[int], k: int) -> int:
        if k<=1:
            return 0
        l,r=0,0
        c,p=0,1
        while(r<len(nums)):
            p*=nums[r]
            while p>=k:
                p//=nums[l]
                l=l+1
            c+=r-l+1
            r+=1
        return c

*1423*
class Solution:
    def maxScore(self, cardPoints: List[int], k: int) -> int:
        n=len(cardPoints)
        s=sum(cardPoints[:k])
        m=s
        for i in range(k):
            s=s-cardPoints[k-1-i]+cardPoints[n-1-i]
            m=max(m,s)
        return m

s= input("Enter password: ")

upper,lower,digit,special=False,False,False,False

for ch in s:
    if ch.isupper():
        upper = True
    elif ch.islower():
        lower = True
    elif ch.isdigit():
        digit = True
    else:
        special = True

if len(s) >= 8 and upper and lower and digit and special:
    print("Valid password")
else:
    print("Invalid password")

*704*
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        l = 0
        r = len(nums) - 1

        while l <= r:
            mid = (l + r) // 2

            if nums[mid] == target:
                return mid
            elif nums[mid] < target:
                l = mid + 1
            else:
                r = mid - 1

        return -1

*35*
class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
        flag=0
        l=0
        r=len(nums)-1
        while l<=r:
            m=(l+r)//2
            if target==nums[m]:
                return m
            elif target > nums[m]:
                l=m+1
            else:
                r=m-1
        return l

*34*
	class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
        res=[-1,-1]
        n=len(nums)
        s,e=0,n-1
        while s<=e:
            m=(s+e)//2
            if nums[m]==target:
                res[0]=m
                e=m-1
            elif nums[m]<target:
                s=m+1
            else:
                e=m-1
        s,e=0,n-1
        while s<=e:
            m=(s+e)//2
            if nums[m]==target:
                res[1]=m
                s=m+1
            elif nums[m]<target:
                s=m+1
            else:
                e=m-1
        return res

*162*
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        n=len(nums)-1
        if n==0:
            return 0
        elif nums[0]>nums[1]:
            return 0
        elif nums[-1]>nums[-2]:
            return n
        s,e=1,n-1
        while s<=e:
            m=(s+e)//2
            if nums[m-1]<nums[m]>nums[m+1]:
                return m
            elif nums[m]<nums[m+1]:
                s=m+1
            else:
                e=m-1

*74*
class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
           row=len(matrix)
           col=len(matrix[0])
           s,e=0,(row*col)-1
           while s<=e:
             m=(s+e)//2
             i=m//col
             j=m%col
             if matrix[i][j]==target:
                return True
             elif matrix[i][j]<target:
                s=m+1
             else:
                e=m-1
           return False

*875*
class Solution:
    def minEatingSpeed(self, piles: List[int], h: int) -> int:
        def can_eat(m,piles,h):
            total=0
            for p in piles:
                total+=math.ceil(p/m)
            if total>h:
                return False
            else:
                return True

        s,e=1,max(piles)
        while s<=e:
            m=(s+e)//2
            if can_eat(m,piles,h):
                e=m-1
            else:
                s=m+1
        return s

*69*
class Solution:
    def mySqrt(self, x: int) -> int:
        if x < 2:
            return x

        left, right = 0, x
        ans = 0

        while left <= right:
            mid = (left + right) // 2

            if mid * mid == x:
                return mid
            elif mid * mid < x:
                ans = mid
                left = mid + 1
            else:
                right = mid - 1

        return ans

*2574*
class Solution:
    def leftRightDifference(self, nums: List[int]) -> List[int]:
        total = sum(nums)
        left = 0
        ans = []

        for num in nums:
            total -= num
            right = total

            ans.append(abs(left - right))

            left += num

        return ans

s="aaaaaabbbbbbccccdddddd"
c,k=1,0
res=""
for i in range(1,len(s)):
    if s[k]==s[i]:
        c+=1
    else:
        res+=s[i-1]+str(c)
        k=i
        c=1
res+=s[-1]+str(c)
print(res)

OR

class Solution:
    def compress(self, chars: List[str]) -> int:
        i = 0
        res = []

        while i < len(chars):
            ch = chars[i]
            count = 0

            while i < len(chars) and chars[i] == ch:
                count += 1
                i += 1

            res.append(ch)

            if count > 1:
                for digit in str(count):
                    res.append(digit)

        for i in range(len(res)):
            chars[i] = res[i]

        return len(res)