# -*- coding: utf-8 -*-
"""Trainingday-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jPTM4f70P3WS8zyBFJnqhRzQsI75dgK
"""

*136*
class Solution:
    def singleNumber(self, nums: List[int]) -> int:
        for i in nums:
            if nums.count(i)==1:
                return i

*66*
class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        for i in range(len(digits)-1,-1,-1):
            if digits[i]==9:
                digits[i]=0
            else:
                digits[i]+=1
                return digits
        return [1]+digits

*268*
class Solution:
    def missingNumber(self, nums: List[int]) -> int:
        expet=sum(nums)
        l=len(nums)
        n=0
        n=l*(l+1)//2
        return n-expet

*231*
class Solution:
    def isPowerOfTwo(self, n: int) -> bool:
       if n<1:
            return False
       while n:
            if n==1:
                return True
            elif n%2!=0:
                return False
            else:
                n=n//2

l=[1,2,3,3,4,4,5,5,6,8,8,7]
m=0
for i in l:
    m=max(m,i)
print(m)

*55*
class Solution:
    def canJump(self, nums: List[int]) -> bool:
        petrol=0
        for p in nums:
            if petrol<0:
                return False
            elif p>petrol:
                petrol=p
            petrol-=1
        return True

l=[4,6,5,7,8,1]
max1,max2=0,0
for i in l:
    if i>max1:
        max2=max1
        max1=i
    elif i>max2 and i!=max1:
        max2=i
print(max2)

l=[1,3,1,3,1,2,1,4,2,2,2,2,2]
d={}
for i in l:
    if i not in d:
        d[i]=1
    else:
        d[i]+=1
ele,max=0,0
for i in d:
    if d[i]>max:
        max=d[i]
        ele=i
print(ele)

n=int(input("enter the population"))
vote=list(map(int,input().split()))
age=list(map(int,input().split()))
c=[0]*(max(vote))
for i in range(n):
    c[vote[i]-1]+=1
m=max(c)
print(c.index(m)+1)

l=list(map(int,input().split()))
temp=l[0]
for i in range(len(l)-1):
    l[i]=l[i+1]
l[len(l)-1]=temp
print(*l)

l=list(map(int,input().split()))
temp1=l[0]
temp2=l[1]
for i in range(len(l)-2):
    l[i]=l[i+2]
l[len(l)-2]=temp1
l[len(l)-1]=temp2
print(*l)